# Default values for ms-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver
containerPort: 8070

image:
   repository: sachinsan2131/eurekaserver
   tag: latest

service:
   type: LoadBalancer
   port: 8070
   targetPort: 8070
   
profile_enabled: true
zipkin_enabled: true 
config_enabled: true 
eureka_enabled: false 
keycloak_enabled: false

