# Default values for ms-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
deploymentName: loans-deployment
deploymentLabel: loans
containerPort: 8090

image:
   repository: sachinsan2131/loans
   tag: latest

service:
   type: ClusterIP
   port: 8090
   targetPort: 8090
   
profile_enabled: true
zipkin_enabled: true 
config_enabled: true 
eureka_enabled: true 

