---
# Source: prod-env/charts/accounts/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: prod-env/charts/cards/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
---
# Source: prod-env/charts/configserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8071
      targetPort: 8071
---
# Source: prod-env/charts/eurekaserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8070
      targetPort: 8070
---
# Source: prod-env/charts/gatewayserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8072
      targetPort: 8072
---
# Source: prod-env/charts/loans/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loans
spec:
  selector:
    app: loans
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
---
# Source: prod-env/charts/zipkin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
---
# Source: prod-env/charts/accounts/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: "sachinsan2131/accounts:latest"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/cards/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
      - name: cards
        image: "sachinsan2131/cards:latest"
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/configserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: "sachinsan2131/configserver:latest"
        ports:
        - containerPort: 8071
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL
---
# Source: prod-env/charts/eurekaserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: "sachinsan2131/eurekaserver:latest"
        ports:
        - containerPort: 8070
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT
---
# Source: prod-env/charts/gatewayserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: gatewayserver
        image: "sachinsan2131/gatewayserver:latest"
        ports:
        - containerPort: 8072
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/loans/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: "sachinsan2131/loans:latest"
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/zipkin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: "openzipkin/zipkin:latest"
        ports:
        - containerPort: 9411
        env:
---
# Source: prod-env/templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: msprod-configmap
data:
  SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
---
# Source: prod-env/charts/accounts/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: prod-env/charts/cards/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
---
# Source: prod-env/charts/configserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8071
      targetPort: 8071
---
# Source: prod-env/charts/eurekaserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8070
      targetPort: 8070
---
# Source: prod-env/charts/gatewayserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8072
      targetPort: 8072
---
# Source: prod-env/charts/loans/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loans
spec:
  selector:
    app: loans
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
---
# Source: prod-env/charts/zipkin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
---
# Source: prod-env/charts/accounts/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: "sachinsan2131/accounts:latest"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/cards/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
      - name: cards
        image: "sachinsan2131/cards:latest"
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/configserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: "sachinsan2131/configserver:latest"
        ports:
        - containerPort: 8071
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL
---
# Source: prod-env/charts/eurekaserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: "sachinsan2131/eurekaserver:latest"
        ports:
        - containerPort: 8070
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT
---
# Source: prod-env/charts/gatewayserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: gatewayserver
        image: "sachinsan2131/gatewayserver:latest"
        ports:
        - containerPort: 8072
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/loans/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: "sachinsan2131/loans:latest"
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_ZIPKIN_BASEURL              
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: SPRING_CONFIG_IMPORT              
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: msprod-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
# Source: prod-env/charts/zipkin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: "openzipkin/zipkin:latest"
        ports:
        - containerPort: 9411
        env:
