global:
  configMapName: msprod-configmap
  zipkinBaseURL: http://zipkin:9411/
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://my-release-my-release-keycloak:80/realms/master/protocol/openid-connect/certs
  tokenuri: http://my-release-keycloak:80/realms/master/protocol/openid-connect/token
  authorizationuri: http://my-release-keycloak:80/realms/master/protocol/openid-connect/auth
  userinfouri: http://my-release-keycloak:80/realms/master/protocol/openid-connect/userinfo
  secretName: msprod-secret
  keycloakclientid: ms-gateway-ui
  keycloakclientsecret: ynQ0skbAapcK8y7v9L8pSrUpxEToNXqH